version: "3.9"
services:
  nginx:
    build:
      context: .
      dockerfile: infra/Dockerfile
    ports:
      - "8080:80"
    volumes:
      - "./proxy:/opt/proxy"
    environment:
      TZ: Asia/Tokyo